// This file will be generated by Supabase CLI
// For now, we'll define the basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string
          name: string
          email: string | null
          phone: string | null
          billing_address: Json | null
          hourly_rate: number
          payment_terms: string
          tax_rate: number
          tax_jurisdiction: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email?: string | null
          phone?: string | null
          billing_address?: Json | null
          hourly_rate?: number
          payment_terms?: string
          tax_rate?: number
          tax_jurisdiction?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string | null
          phone?: string | null
          billing_address?: Json | null
          hourly_rate?: number
          payment_terms?: string
          tax_rate?: number
          tax_jurisdiction?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      boats: {
        Row: {
          id: string
          client_id: string
          name: string
          make: string | null
          model: string | null
          year: number | null
          length: number | null
          onedrive_folder_id: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          client_id: string
          name: string
          make?: string | null
          model?: string | null
          year?: number | null
          length?: number | null
          onedrive_folder_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_id?: string
          name?: string
          make?: string | null
          model?: string | null
          year?: number | null
          length?: number | null
          onedrive_folder_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add more table types as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
